name: ğŸš€ CI

on:
  pull_request:
    branches:
      - main

env:
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  CONTENTFUL_CODEGEN_TOKEN: ${{ secrets.CONTENTFUL_CODEGEN_TOKEN }}
  CONTENTFUL_ACCESS_TOKEN=: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs ğŸ›‘
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Checkout ğŸ›
        uses: actions/checkout@v4

      - name: Setup node â”
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install NPM dependencies ğŸ“¦
        uses: bahmutov/npm-install@v1

      - name: Build project ğŸ‘·â€â™€ï¸
        run: npm run build

      - name: Run E2E tests ğŸŒ³
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run start
          wait-on: http://localhost:3000
          config: baseUrl=http://localhost:3000
          browser: chrome
          spec: cypress/e2e/*

      - name: Run Component tests ğŸ§ª
        uses: cypress-io/github-action@v6
        with:
          install: false
          component: true
          browser: chrome
