name: ğŸš€ CI

on:
  pull_request:
    branches:
      - main

env:
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  CONTENTFUL_CODEGEN_TOKEN: ${{ secrets.CONTENTFUL_CODEGEN_TOKEN }}
  CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
  NEXT_PUBLIC_API_MOCKING: true

jobs:
  install-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs ğŸ›‘
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Checkout ğŸ›
        uses: actions/checkout@v4

      - name: Setup node â”
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache dependencies ğŸ“
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: |
            **/node_modules
            ~/.cache/Cypress
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}-cypress-${{ hashFiles('**/package.json') }}

      - name: Install NPM dependencies ğŸ“¦
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build project ğŸ‘·â€â™€ï¸
        run: npm run build

      - name: List .next directory contents
        run: ls -la .next

      - name: Upload build artifacts ğŸº
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: .next/**/*
          if-no-files-found: error

  run-tests:
    needs: install-and-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v4

      - name: Setup node â”
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache dependencies ğŸ“
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            ~/.cache/Cypress
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}-cypress-${{ hashFiles('**/package.json') }}

      - name: Download build artifacts ğŸ“¥
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .next

      - name: Verify Cypress ğŸ”
        run: npx cypress verify

      - name: Run Component tests ğŸ§ª
        uses: cypress-io/github-action@v6
        with:
          install: false
          component: true
          browser: chrome

      - name: Run E2E tests ğŸŒ³
        uses: cypress-io/github-action@v6
        with:
          install: false
          start: npm run start
          wait-on: http://localhost:3000
          config: baseUrl=http://localhost:3000
          browser: chrome
          spec: cypress/e2e/*

      - name: Upload Cypress failure screenshots ğŸ“¸
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
